import businessType from "../../../configs/business-type";
// const businessType = [
//     {
//         text: 'None',
//         value: 'off'
//     },
//     {
//         text: 'Organization',
//         value: 'Organization'
//     },
// ]

export default [
    {
        field: "person_or_company_section",
        type: "alias",
        schema: null,
        meta: {
            field: "person_or_company_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Person or Company Section",
    },
    {
        field: "person_or_company_left",
        type: "alias",
        schema: null,
        meta: {
            field: "person_or_company_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "person_or_company_section",
            validation: null,
            validation_message: null,
        },
        name: "Person or Company Left",
    },
    {
        field: "person_or_company_title",
        type: "alias",
        schema: null,
        meta: {
            field: "person_or_company_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Person or Company",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "person_or_company_left",
            validation: null,
            validation_message: null,
        },
        name: "Person or Company Title",
    },
    {
        field: "person_or_company_right",
        type: "alias",
        schema: null,
        meta: {
            field: "person_or_company_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "person_or_company_section",
            validation: null,
            validation_message: null,
        },
        name: "Person or Company Right",
    },
    {
        field: "local_type",
        type: "string",
        schema: {
            data_type: "varchar",
            default_value: "organization",
            max_length: 255,
        },
        meta: {
            field: "local_type",
            special: null,
            interface: "radio-button",
            options: {
                choices: [
                    {
                        text: "Person",
                        value: "person",
                        iconOn: null,
                        iconOff: null,
                    },
                    {
                        text: "Organization",
                        value: "organization",
                        iconOn: null,
                        iconOff: null,
                    },
                ],
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: "Choose whether the site represents a person or an organization.",
            conditions: null,
            required: false,
            group: "person_or_company_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "website_name_section",
        type: "alias",
        schema: null,
        meta: {
            field: "website_name_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 4,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Website Name Section",
    },
    {
        field: "website_name_left",
        type: "alias",
        schema: null,
        meta: {
            field: "website_name_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "website_name_section",
            validation: null,
            validation_message: null,
        },
        name: "Website Name Left",
    },
    {
        field: "website_name_title",
        type: "alias",
        schema: null,
        meta: {
            field: "website_name_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Website Name",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "website_name_left",
            validation: null,
            validation_message: null,
        },
        name: "Website Name Title",
    },
    {
        field: "website_name_right",
        type: "alias",
        schema: null,
        meta: {
            field: "website_name_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "website_name_section",
            validation: null,
            validation_message: null,
        },
        name: "Website Name Right",
    },
    {
        field: "website_name",
        type: "string",
        schema: {
            name: "website_name",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            is_nullable: true,
        },
        meta: {
            field: "website_name",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: [
                {
                    language: "en-US",
                    translation: "",
                },
            ],
            note: "Enter the name of your site to appear in search results.",
            conditions: null,
            required: false,
            group: "website_name_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "website_alternate_name_section",
        type: "alias",
        schema: null,
        meta: {
            field: "website_alternate_name_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 5,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Website Alternate Name Section",
    },
    {
        field: "website_alternate_name_left",
        type: "alias",
        schema: null,
        meta: {
            field: "website_alternate_name_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "website_alternate_name_section",
            validation: null,
            validation_message: null,
        },
        name: "Website Alternate Name Left",
    },
    {
        field: "website_alternate_name_title",
        type: "alias",
        schema: null,
        meta: {
            field: "website_alternate_name_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Website Alternate Name",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "website_alternate_name_left",
            validation: null,
            validation_message: null,
        },
        name: "Website Alternate Name Title",
    },
    {
        field: "website_alternate_name_right",
        type: "alias",
        schema: null,
        meta: {
            field: "website_alternate_name_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "website_alternate_name_section",
            validation: null,
            validation_message: null,
        },
        name: "Website Alternate Name Right",
    },
    {
        field: "website_alternate_name",
        type: "string",
        schema: {
            data_type: "varchar",
            default_value: null,
            max_length: 255,
        },
        meta: {
            field: "website_alternate_name",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: "An alternate version of your site name (for example, an acronym or shorter name).",
            conditions: null,
            required: false,
            group: "website_alternate_name_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "name_section",
        type: "alias",
        schema: null,
        meta: {
            field: "name_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 6,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "hide organization",
                    rule: {
                        _and: [
                            {
                                local_type: {
                                    _neq: "organization",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {},
                },
            ],
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Name Section",
    },
    {
        field: "name_left",
        type: "alias",
        schema: null,
        meta: {
            field: "name_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "name_section",
            validation: null,
            validation_message: null,
        },
        name: "Name Left",
    },
    {
        field: "name_tile",
        type: "alias",
        schema: null,
        meta: {
            field: "name_tile",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Person/Organization Name",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "name_left",
            validation: null,
            validation_message: null,
        },
        name: "Name Tile",
    },
    {
        field: "name_right",
        type: "alias",
        schema: null,
        meta: {
            field: "name_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "name_section",
            validation: null,
            validation_message: null,
        },
        name: "Name Right",
    },
    {
        field: "name",
        type: "string",
        schema: {
            data_type: "varchar",
            default_value: null,
            max_length: 255,
        },
        meta: {
            field: "name",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: [
                {
                    language: "en-US",
                    translation: "",
                },
            ],
            note: null,
            conditions: null,
            required: false,
            group: "name_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "logo_section",
        type: "alias",
        schema: null,
        meta: {
            field: "logo_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 7,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Logo Section",
    },
    {
        field: "logo_left",
        type: "alias",
        schema: null,
        meta: {
            field: "logo_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "logo_section",
            validation: null,
            validation_message: null,
        },
        name: "Logo Left",
    },
    {
        field: "logo_title",
        type: "alias",
        schema: null,
        meta: {
            field: "logo_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Logo",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "logo_left",
            validation: null,
            validation_message: null,
        },
        name: "Logo Title",
    },
    {
        field: "logo_right",
        type: "alias",
        schema: null,
        meta: {
            field: "logo_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "logo_section",
            validation: null,
            validation_message: null,
        },
        name: "Logo Right",
    },
    {
        field: "logo",
        type: "uuid",
        meta: {
            special: null,
            interface: "image-upload",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 5,
            width: "full",
            note: null,
            conditions: null,
            required: false,
            group: "logo_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "url_section",
        type: "alias",
        schema: null,
        meta: {
            field: "url_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 8,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "URL Section",
    },
    {
        field: "url_left",
        type: "alias",
        schema: null,
        meta: {
            field: "url_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "url_section",
            validation: null,
            validation_message: null,
        },
        name: "URL Left",
    },
    {
        field: "url_title",
        type: "alias",
        schema: null,
        meta: {
            field: "url_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "URL",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "url_left",
            validation: null,
            validation_message: null,
        },
        name: "URL Title",
    },
    {
        field: "url_right",
        type: "alias",
        schema: null,
        meta: {
            field: "url_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "url_section",
            validation: null,
            validation_message: null,
        },
        name: "URL Right",
    },
    {
        field: "url",
        type: "string",
        schema: {
            data_type: "varchar",
            default_value: null,
            max_length: 255,
        },
        meta: {
            field: "url",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: [
                {
                    language: "en-US",
                    translation: "",
                },
            ],
            note: null,
            conditions: null,
            required: false,
            group: "url_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "email_section",
        type: "alias",
        schema: null,
        meta: {
            field: "email_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 9,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Email Section",
    },
    {
        field: "email_left",
        type: "alias",
        schema: null,
        meta: {
            field: "email_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "email_section",
            validation: null,
            validation_message: null,
        },
        name: "Email Left",
    },
    {
        field: "email_title",
        type: "alias",
        schema: null,
        meta: {
            field: "email_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Email",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "email_left",
            validation: null,
            validation_message: null,
        },
        name: "Email Title",
    },
    {
        field: "email_right",
        type: "alias",
        schema: null,
        meta: {
            field: "email_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "email_section",
            validation: null,
            validation_message: null,
        },
        name: "Email Right",
    },
    {
        field: "email",
        type: "string",
        schema: null,
        meta: {
            field: "email",
            special: null,
            interface: "input",
            options: {},
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "email_right",
            validation: {
                _and: [
                    {
                        email: {
                            _regex: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$",
                        },
                    },
                ],
            },
            validation_message: "Invalid email format!",
        },
        name: "",
    },
    {
        field: "phone_number_section",
        type: "alias",
        schema: null,
        meta: {
            field: "phone_number_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 10,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Phone Number Section",
    },
    {
        field: "phone_number_left",
        type: "alias",
        schema: null,
        meta: {
            field: "phone_number_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "phone_number_section",
            validation: null,
            validation_message: null,
        },
        name: "Phone Number Left",
    },
    {
        field: "phone_number_title",
        type: "alias",
        schema: null,
        meta: {
            field: "phone_number_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Phone Number",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "phone_number_left",
            validation: null,
            validation_message: null,
        },
        name: "Phone Number Title",
    },
    {
        field: "phone_number_right",
        type: "alias",
        schema: null,
        meta: {
            field: "phone_number_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "phone_number_section",
            validation: null,
            validation_message: null,
        },
        name: "Phone Number Right",
    },
    {
        field: "address_section",
        type: "alias",
        schema: null,
        meta: {
            field: "address_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 11,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Address Section",
    },
    {
        field: "address_left",
        type: "alias",
        schema: null,
        meta: {
            field: "address_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "address_section",
            validation: null,
            validation_message: null,
        },
        name: "Address Left",
    },
    {
        field: "address_title",
        type: "alias",
        schema: null,
        meta: {
            field: "address_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Address",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "address_left",
            validation: null,
            validation_message: null,
        },
        name: "Address Title",
    },
    {
        field: "address_right",
        type: "alias",
        schema: null,
        meta: {
            field: "address_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "address_section",
            validation: null,
            validation_message: null,
        },
        name: "Address Right",
    },
    {
        field: "street_address",
        type: "string",
        schema: {
            default_value: null,
            max_length: 255,
        },
        meta: {
            field: "street_address",
            special: null,
            interface: "input",
            options: {
                placeholder: "Street address",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            note: null,
            conditions: null,
            required: false,
            group: "address_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "locality",
        type: "string",
        schema: {
            default_value: null,
            max_length: 255,
        },
        meta: {
            field: "locality",
            special: null,
            interface: "input",
            options: {
                placeholder: "Locality",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            note: null,
            conditions: null,
            required: false,
            group: "address_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "region",
        type: "string",
        schema: {
            default_value: null,
            max_length: 255,
        },
        meta: {
            field: "region",
            special: null,
            interface: "input",
            options: {
                placeholder: "Region",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 3,
            width: "full",
            note: null,
            conditions: null,
            required: false,
            group: "address_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "postal_code",
        type: "string",
        schema: {
            default_value: null,
            max_length: 255,
        },
        meta: {
            field: "postal_code",
            special: null,
            interface: "input",
            options: {
                placeholder: "Postal code",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 4,
            width: "full",
            note: null,
            conditions: null,
            required: false,
            group: "address_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "country",
        type: "string",
        schema: {
            default_value: null,
            max_length: 255,
        },
        meta: {
            field: "country",
            special: null,
            interface: "input",
            options: {
                placeholder: "Country",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 5,
            width: "full",
            note: null,
            conditions: null,
            required: false,
            group: "address_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "business_type_section",
        type: "alias",
        schema: null,
        meta: {
            field: "business_type_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "show_business_type",
                    rule: {
                        _and: [
                            {
                                local_type: {
                                    _neq: "organization",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {},
                },
            ],
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Business Type Section",
    },
    {
        field: "business_type_left",
        type: "alias",
        schema: null,
        meta: {
            field: "business_type_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "business_type_section",
            validation: null,
            validation_message: null,
        },
        name: "Business Type Left",
    },
    {
        field: "business_type_title",
        type: "alias",
        schema: null,
        meta: {
            field: "business_type_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Business Type",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "business_type_left",
            validation: null,
            validation_message: null,
        },
        name: "Business Type Title",
    },
    {
        field: "business_type_right",
        type: "alias",
        schema: null,
        meta: {
            field: "business_type_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "business_type_section",
            validation: null,
            validation_message: null,
        },
        name: "Business Type Right",
    },
    {
        field: "business_type",
        type: "string",
        meta: {
            field: "business_type",
            special: null,
            interface: "select-dropdown",
            options: {
                choices: businessType,
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            conditions: null,
            required: false,
            group: "business_type_right",
            validation: null,
            validation_message: null,
        },
        schema: {
            default_value: "Organization",
        },
    },
];
