export default [
    {
        field: "default_meta_info",
        type: "alias",
        schema: null,
        meta: {
            id: 12,
            field: "default_meta_info",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Default Meta Info",
    },
    {
        field: "default_meta_info_left",
        type: "alias",
        schema: null,
        meta: {
            id: 15,
            field: "default_meta_info_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "default_meta_info",
            validation: null,
            validation_message: null,
        },
        name: "Default Meta Info Left",
    },
    {
        field: "default_meta_info_title",
        type: "alias",
        schema: null,
        meta: {
            id: 17,
            field: "default_meta_info_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Default meta info",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "default_meta_info_left",
            validation: null,
            validation_message: null,
        },
        name: "Default Meta Info Title",
    },
    {
        field: "default_meta_info_right",
        type: "alias",
        schema: null,
        meta: {
            id: 16,
            field: "default_meta_info_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "default_meta_info",
            validation: null,
            validation_message: null,
        },
        name: "Default Meta Info Right",
    },
    {
        field: "meta_title",
        type: "string",
        schema: {
            name: "meta_title",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 6,
            field: "meta_title",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: "Default title tag for single all pages. This can be changed on a per-post basis on the content detail screen.",
            conditions: null,
            required: false,
            group: "default_meta_info_right",
            validation: null,
            validation_message: null,
        },
        name: "Meta Title",
    },
    {
        field: "meta_description",
        type: "text",
        schema: {
            name: "meta_description",
            data_type: "text",
            default_value: null,
            max_length: null,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 7,
            field: "meta_description",
            special: null,
            interface: "input-multiline",
            options: {
                softLength: 255,
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: "Default meta title for single all pages. This can be changed on a per-post basis on the content detail screen.",
            conditions: null,
            required: false,
            group: "default_meta_info_right",
            validation: null,
            validation_message: null,
        },
        name: "Meta Description",
    },
    {
        field: "social_sharing_section",
        type: "alias",
        schema: null,
        meta: {
            id: 8,
            field: "social_sharing_section",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 3,
            width: "full",
            translations: null,
            note: "Add social account information to your website's Schema and Open Graph.[Learn More](http://codihaus.com).",
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Social Sharing Section",
    },
    {
        field: "social_sharing_left",
        type: "alias",
        schema: null,
        meta: {
            id: 9,
            field: "social_sharing_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "social_sharing_section",
            validation: null,
            validation_message: null,
        },
        name: "Social Sharing Left",
    },
    {
        field: "social_sharing_title",
        type: "alias",
        schema: null,
        meta: {
            id: 11,
            field: "social_sharing_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Social sharing",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: "Add social account information to your website's Schema and Open Graph.[Learn More](http://codihaus.com).",
            conditions: null,
            required: false,
            group: "social_sharing_left",
            validation: null,
            validation_message: null,
        },
        name: "Social Sharing Title",
    },
    {
        field: "social_sharing_right",
        type: "alias",
        schema: null,
        meta: {
            id: 10,
            field: "social_sharing_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "social_sharing_section",
            validation: null,
            validation_message: null,
        },
        name: "Social Sharing Right",
    },
    {
        field: "social_sharing_tab",
        type: "string",
        schema: {
            name: "social_sharing_tab",
            data_type: "varchar",
            default_value: "facebook",
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 35,
            field: "social_sharing_tab",
            special: null,
            interface: "radio-button",
            options: {
                choices: [
                    {
                        text: "Facebook",
                        value: "facebook",
                    },
                    {
                        text: "Twitter",
                        value: "twitter",
                    },
                ],
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "social_sharing_right",
            validation: null,
            validation_message: null,
        },
        name: "",
    },
    {
        field: "facebook_title",
        type: "string",
        schema: {
            name: "facebook_title",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 36,
            field: "facebook_title",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "social_facebook",
                    rule: {
                        _and: [
                            {
                                social_sharing_tab: {
                                    _neq: "facebook",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {
                        font: "sans-serif",
                        trim: false,
                        masked: false,
                        clear: false,
                        slug: false,
                    },
                },
            ],
            required: false,
            group: "social_sharing_right",
            validation: null,
            validation_message: null,
        },
        name: "Facebook Title",
    },
    {
        field: "facebook_page_url",
        type: "string",
        schema: {
            name: "facebook_page_url",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 37,
            field: "facebook_page_url",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "social_facebook",
                    rule: {
                        _and: [
                            {
                                social_sharing_tab: {
                                    _neq: "facebook",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {
                        font: "sans-serif",
                        trim: false,
                        masked: false,
                        clear: false,
                        slug: false,
                    },
                },
            ],
            required: false,
            group: "social_sharing_right",
            validation: null,
            validation_message: null,
        },
        name: "Facebook Page URL",
    },
    {
        field: "facebook_authorship",
        type: "string",
        schema: {
            name: "facebook_authorship",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 38,
            field: "facebook_authorship",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 4,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "social_facebook",
                    rule: {
                        _and: [
                            {
                                social_sharing_tab: {
                                    _neq: "facebook",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {
                        font: "sans-serif",
                        trim: false,
                        masked: false,
                        clear: false,
                        slug: false,
                    },
                },
            ],
            required: false,
            group: "social_sharing_right",
            validation: null,
            validation_message: null,
        },
        name: "Facebook Authorship",
    },
    {
        field: "facebook_admin",
        type: "string",
        schema: {
            name: "facebook_admin",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 39,
            field: "facebook_admin",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 5,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "social_facebook",
                    rule: {
                        _and: [
                            {
                                social_sharing_tab: {
                                    _neq: "facebook",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {
                        font: "sans-serif",
                        trim: false,
                        masked: false,
                        clear: false,
                        slug: false,
                    },
                },
            ],
            required: false,
            group: "social_sharing_right",
            validation: null,
            validation_message: null,
        },
        name: "Facebook Admin",
    },
    {
        field: "facebook_app",
        type: "string",
        schema: {
            name: "facebook_app",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 40,
            field: "facebook_app",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 6,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "social_facebook",
                    rule: {
                        _and: [
                            {
                                social_sharing_tab: {
                                    _neq: "facebook",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {
                        font: "sans-serif",
                        trim: false,
                        masked: false,
                        clear: false,
                        slug: false,
                    },
                },
            ],
            required: false,
            group: "social_sharing_right",
            validation: null,
            validation_message: null,
        },
        name: "Facebook App",
    },
    {
        field: "facebook_secret",
        type: "string",
        schema: {
            name: "facebook_secret",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 41,
            field: "facebook_secret",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 7,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "social_facebook",
                    rule: {
                        _and: [
                            {
                                social_sharing_tab: {
                                    _neq: "facebook",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {
                        font: "sans-serif",
                        trim: false,
                        masked: false,
                        clear: false,
                        slug: false,
                    },
                },
            ],
            required: false,
            group: "social_sharing_right",
            validation: null,
            validation_message: null,
        },
        name: "Facebook Secret",
    },
    {
        field: "twitter_title",
        type: "string",
        schema: {
            name: "twitter_title",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 42,
            field: "twitter_title",
            special: null,
            interface: "input",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 8,
            width: "full",
            translations: null,
            note: null,
            conditions: [
                {
                    name: "social_twitter",
                    rule: {
                        _and: [
                            {
                                social_sharing_tab: {
                                    _neq: "twitter",
                                },
                            },
                        ],
                    },
                    hidden: true,
                    options: {
                        font: "sans-serif",
                        trim: false,
                        masked: false,
                        clear: false,
                        slug: false,
                    },
                },
            ],
            required: false,
            group: "social_sharing_right",
            validation: null,
            validation_message: null,
        },
        name: "Twitter Title",
    },
    {
        field: "site_connections",
        type: "alias",
        schema: null,
        meta: {
            id: 24,
            field: "site_connections",
            special: ["alias", "no-data", "group"],
            interface: "group-section",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 3,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: null,
            validation: null,
            validation_message: null,
        },
        name: "Site Connections",
    },
    {
        field: "site_connection_left",
        type: "alias",
        schema: null,
        meta: {
            id: 25,
            field: "site_connection_left",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "site_connections",
            validation: null,
            validation_message: null,
        },
        name: "Site Connection Left",
    },
    {
        field: "site_connection_title",
        type: "alias",
        schema: null,
        meta: {
            id: 27,
            field: "site_connection_title",
            special: ["alias", "no-data"],
            interface: "presentation-info",
            options: {
                title: "Site connections",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: "Verify your site with different tools. This will add a verification meta tag to your homepage.",
            conditions: null,
            required: false,
            group: "site_connection_left",
            validation: null,
            validation_message: null,
        },
        name: "Site Connection Title",
    },
    {
        field: "site_connection_right",
        type: "alias",
        schema: null,
        meta: {
            id: 26,
            field: "site_connection_right",
            special: ["alias", "no-data", "group"],
            interface: "group-column",
            options: null,
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: null,
            conditions: null,
            required: false,
            group: "site_connections",
            validation: null,
            validation_message: null,
        },
        name: "Site Connection Right",
    },
    {
        field: "google_verification_code",
        type: "string",
        schema: {
            name: "google_verification_code",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 28,
            field: "google_verification_code",
            special: null,
            interface: "input",
            options: {
                placeholder: "Add verification code",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 1,
            width: "full",
            translations: null,
            note: "Get your verification code in [Google Search console](https://search.google.com/search-console/).",
            conditions: null,
            required: false,
            group: "site_connection_right",
            validation: null,
            validation_message: null,
        },
        name: "Google Verification Code",
    },
    {
        field: "bing_verification_code",
        type: "string",
        schema: {
            name: "bing_verification_code",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 29,
            field: "bing_verification_code",
            special: null,
            interface: "input",
            options: {
                placeholder: "Add verification code",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 2,
            width: "full",
            translations: null,
            note: "Get your verification code in [Bing Webmaster Tools](https://www.bing.com/webmasters/about).",
            conditions: null,
            required: false,
            group: "site_connection_right",
            validation: null,
            validation_message: null,
        },
        name: "Bing Verification Code",
    },
    {
        field: "pinterest_verification_code",
        type: "string",
        schema: {
            name: "pinterest_verification_code",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 30,
            field: "pinterest_verification_code",
            special: null,
            interface: "input",
            options: {
                placeholder: "Add verification code",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 3,
            width: "full",
            translations: null,
            note: "Claim your site over at Pinterest.",
            conditions: null,
            required: false,
            group: "site_connection_right",
            validation: null,
            validation_message: null,
        },
        name: "Pinterest Verification Code",
    },
    {
        field: "yandex_verification_code",
        type: "string",
        schema: {
            name: "yandex_verification_code",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 31,
            field: "yandex_verification_code",
            special: null,
            interface: "input",
            options: {
                placeholder: "Add verification code",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 4,
            width: "full",
            translations: null,
            note: "Get your verification code in [Yandex Webmaster tools](https://webmaster.yandex.com/).",
            conditions: null,
            required: false,
            group: "site_connection_right",
            validation: null,
            validation_message: null,
        },
        name: "Yandex Verification Code",
    },
    {
        field: "baidu_verification_code",
        type: "string",
        schema: {
            name: "baidu_verification_code",
            data_type: "varchar",
            default_value: null,
            max_length: 255,
            numeric_precision: null,
            numeric_scale: null,
            is_generated: false,
            generation_expression: null,
            is_nullable: true,
            is_unique: false,
            is_primary_key: false,
            has_auto_increment: false,
            foreign_key_column: null,
            foreign_key_table: null,
        },
        meta: {
            id: 32,
            field: "baidu_verification_code",
            special: null,
            interface: "input",
            options: {
                placeholder: "Add verification code",
            },
            display: null,
            display_options: null,
            readonly: false,
            hidden: false,
            sort: 5,
            width: "full",
            translations: null,
            note: "Get your verification code in [Baidu Webmaster tools](https://ziyuan.baidu.com/login/index?u=/site/siteadd).",
            conditions: null,
            required: false,
            group: "site_connection_right",
            validation: null,
            validation_message: null,
        },
        name: "Baidu Verification Code",
    },
];
